package test.model;


import java.util.Date;

public class AttrValues {
    
    private Integer id;

    private Integer attrid;

    private String attrname;

    private String attrvalue;

    private String extid;

    private Integer status;

    private Date createdat;

    private Integer createdby;

    private Date updatedat;

    private Integer updatedby;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAttrid() {
        return attrid;
    }

    
    public void setAttrid(Integer attrid) {
        this.attrid = attrid;
    }

   
    public String getAttrname() {
        return attrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.AttrName
     *
     * @param attrname the value for ch_attr_values.AttrName
     *
     * @mbggenerated
     */
    public void setAttrname(String attrname) {
        this.attrname = attrname == null ? null : attrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_attr_values.AttrValue
     *
     * @return the value of ch_attr_values.AttrValue
     *
     * @mbggenerated
     */
    public String getAttrvalue() {
        return attrvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.AttrValue
     *
     * @param attrvalue the value for ch_attr_values.AttrValue
     *
     * @mbggenerated
     */
    public void setAttrvalue(String attrvalue) {
        this.attrvalue = attrvalue == null ? null : attrvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_attr_values.ExtID
     *
     * @return the value of ch_attr_values.ExtID
     *
     * @mbggenerated
     */
    public String getExtid() {
        return extid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.ExtID
     *
     * @param extid the value for ch_attr_values.ExtID
     *
     * @mbggenerated
     */
    public void setExtid(String extid) {
        this.extid = extid == null ? null : extid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_attr_values.Status
     *
     * @return the value of ch_attr_values.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.Status
     *
     * @param status the value for ch_attr_values.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_attr_values.CreatedAt
     *
     * @return the value of ch_attr_values.CreatedAt
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.CreatedAt
     *
     * @param createdat the value for ch_attr_values.CreatedAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_attr_values.CreatedBy
     *
     * @return the value of ch_attr_values.CreatedBy
     *
     * @mbggenerated
     */
    public Integer getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.CreatedBy
     *
     * @param createdby the value for ch_attr_values.CreatedBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_attr_values.UpdatedAt
     *
     * @return the value of ch_attr_values.UpdatedAt
     *
     * @mbggenerated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.UpdatedAt
     *
     * @param updatedat the value for ch_attr_values.UpdatedAt
     *
     * @mbggenerated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_attr_values.UpdatedBy
     *
     * @return the value of ch_attr_values.UpdatedBy
     *
     * @mbggenerated
     */
    public Integer getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_attr_values.UpdatedBy
     *
     * @param updatedby the value for ch_attr_values.UpdatedBy
     *
     * @mbggenerated
     */
    public void setUpdatedby(Integer updatedby) {
        this.updatedby = updatedby;
    }
}