import java.math.BigDecimal;
import java.util.Date;

public class ChSellPool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.ItemsID
     *
     * @mbggenerated
     */
    private Integer itemsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.customerId
     *
     * @mbggenerated
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.quantity
     *
     * @mbggenerated
     */
    private Float quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.unit
     *
     * @mbggenerated
     */
    private Integer unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.ware_province
     *
     * @mbggenerated
     */
    private Integer wareProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.ware_id
     *
     * @mbggenerated
     */
    private Integer wareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.ware_name
     *
     * @mbggenerated
     */
    private String wareName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.priority
     *
     * @mbggenerated
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.commands
     *
     * @mbggenerated
     */
    private String commands;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.createdAt
     *
     * @mbggenerated
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.createdBy
     *
     * @mbggenerated
     */
    private Integer createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.updatedAt
     *
     * @mbggenerated
     */
    private Date updatedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.updatedBy
     *
     * @mbggenerated
     */
    private Integer updatedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.volume
     *
     * @mbggenerated
     */
    private Integer volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.mall_sale_id
     *
     * @mbggenerated
     */
    private Integer mallSaleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.mall_user_account
     *
     * @mbggenerated
     */
    private String mallUserAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.paytype
     *
     * @mbggenerated
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.receipttype
     *
     * @mbggenerated
     */
    private Integer receipttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.delivery
     *
     * @mbggenerated
     */
    private Integer delivery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.deliverytime
     *
     * @mbggenerated
     */
    private String deliverytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.moq
     *
     * @mbggenerated
     */
    private String moq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.outmoq
     *
     * @mbggenerated
     */
    private String outmoq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.overflow
     *
     * @mbggenerated
     */
    private String overflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.lastPriceType
     *
     * @mbggenerated
     */
    private Integer lastpricetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.lastPrice
     *
     * @mbggenerated
     */
    private BigDecimal lastprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.lastCustomerId
     *
     * @mbggenerated
     */
    private Integer lastcustomerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.lastMallAccount
     *
     * @mbggenerated
     */
    private String lastmallaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.lastCustomerName
     *
     * @mbggenerated
     */
    private String lastcustomername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.poolPriceCount
     *
     * @mbggenerated
     */
    private Integer poolpricecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.lastTime
     *
     * @mbggenerated
     */
    private String lasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.isConfirm
     *
     * @mbggenerated
     */
    private Integer isconfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.orderId
     *
     * @mbggenerated
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.priceType
     *
     * @mbggenerated
     */
    private Integer pricetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.isClose
     *
     * @mbggenerated
     */
    private Integer isclose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.initPrice
     *
     * @mbggenerated
     */
    private BigDecimal initprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.FuturesMonth
     *
     * @mbggenerated
     */
    private String futuresmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ch_sell_pool.initPriceType
     *
     * @mbggenerated
     */
    private Integer initpricetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.id
     *
     * @return the value of ch_sell_pool.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.id
     *
     * @param id the value for ch_sell_pool.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.ItemsID
     *
     * @return the value of ch_sell_pool.ItemsID
     *
     * @mbggenerated
     */
    public Integer getItemsid() {
        return itemsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.ItemsID
     *
     * @param itemsid the value for ch_sell_pool.ItemsID
     *
     * @mbggenerated
     */
    public void setItemsid(Integer itemsid) {
        this.itemsid = itemsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.customerId
     *
     * @return the value of ch_sell_pool.customerId
     *
     * @mbggenerated
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.customerId
     *
     * @param customerid the value for ch_sell_pool.customerId
     *
     * @mbggenerated
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.quantity
     *
     * @return the value of ch_sell_pool.quantity
     *
     * @mbggenerated
     */
    public Float getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.quantity
     *
     * @param quantity the value for ch_sell_pool.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.unit
     *
     * @return the value of ch_sell_pool.unit
     *
     * @mbggenerated
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.unit
     *
     * @param unit the value for ch_sell_pool.unit
     *
     * @mbggenerated
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.ware_province
     *
     * @return the value of ch_sell_pool.ware_province
     *
     * @mbggenerated
     */
    public Integer getWareProvince() {
        return wareProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.ware_province
     *
     * @param wareProvince the value for ch_sell_pool.ware_province
     *
     * @mbggenerated
     */
    public void setWareProvince(Integer wareProvince) {
        this.wareProvince = wareProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.ware_id
     *
     * @return the value of ch_sell_pool.ware_id
     *
     * @mbggenerated
     */
    public Integer getWareId() {
        return wareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.ware_id
     *
     * @param wareId the value for ch_sell_pool.ware_id
     *
     * @mbggenerated
     */
    public void setWareId(Integer wareId) {
        this.wareId = wareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.ware_name
     *
     * @return the value of ch_sell_pool.ware_name
     *
     * @mbggenerated
     */
    public String getWareName() {
        return wareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.ware_name
     *
     * @param wareName the value for ch_sell_pool.ware_name
     *
     * @mbggenerated
     */
    public void setWareName(String wareName) {
        this.wareName = wareName == null ? null : wareName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.price
     *
     * @return the value of ch_sell_pool.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.price
     *
     * @param price the value for ch_sell_pool.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.priority
     *
     * @return the value of ch_sell_pool.priority
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.priority
     *
     * @param priority the value for ch_sell_pool.priority
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.commands
     *
     * @return the value of ch_sell_pool.commands
     *
     * @mbggenerated
     */
    public String getCommands() {
        return commands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.commands
     *
     * @param commands the value for ch_sell_pool.commands
     *
     * @mbggenerated
     */
    public void setCommands(String commands) {
        this.commands = commands == null ? null : commands.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.status
     *
     * @return the value of ch_sell_pool.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.status
     *
     * @param status the value for ch_sell_pool.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.createdAt
     *
     * @return the value of ch_sell_pool.createdAt
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.createdAt
     *
     * @param createdat the value for ch_sell_pool.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.createdBy
     *
     * @return the value of ch_sell_pool.createdBy
     *
     * @mbggenerated
     */
    public Integer getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.createdBy
     *
     * @param createdby the value for ch_sell_pool.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.updatedAt
     *
     * @return the value of ch_sell_pool.updatedAt
     *
     * @mbggenerated
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.updatedAt
     *
     * @param updatedat the value for ch_sell_pool.updatedAt
     *
     * @mbggenerated
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.updatedBy
     *
     * @return the value of ch_sell_pool.updatedBy
     *
     * @mbggenerated
     */
    public Integer getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.updatedBy
     *
     * @param updatedby the value for ch_sell_pool.updatedBy
     *
     * @mbggenerated
     */
    public void setUpdatedby(Integer updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.code
     *
     * @return the value of ch_sell_pool.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.code
     *
     * @param code the value for ch_sell_pool.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.volume
     *
     * @return the value of ch_sell_pool.volume
     *
     * @mbggenerated
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.volume
     *
     * @param volume the value for ch_sell_pool.volume
     *
     * @mbggenerated
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.commodity_id
     *
     * @return the value of ch_sell_pool.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.commodity_id
     *
     * @param commodityId the value for ch_sell_pool.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.mall_sale_id
     *
     * @return the value of ch_sell_pool.mall_sale_id
     *
     * @mbggenerated
     */
    public Integer getMallSaleId() {
        return mallSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.mall_sale_id
     *
     * @param mallSaleId the value for ch_sell_pool.mall_sale_id
     *
     * @mbggenerated
     */
    public void setMallSaleId(Integer mallSaleId) {
        this.mallSaleId = mallSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.mall_user_account
     *
     * @return the value of ch_sell_pool.mall_user_account
     *
     * @mbggenerated
     */
    public String getMallUserAccount() {
        return mallUserAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.mall_user_account
     *
     * @param mallUserAccount the value for ch_sell_pool.mall_user_account
     *
     * @mbggenerated
     */
    public void setMallUserAccount(String mallUserAccount) {
        this.mallUserAccount = mallUserAccount == null ? null : mallUserAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.paytype
     *
     * @return the value of ch_sell_pool.paytype
     *
     * @mbggenerated
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.paytype
     *
     * @param paytype the value for ch_sell_pool.paytype
     *
     * @mbggenerated
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.receipttype
     *
     * @return the value of ch_sell_pool.receipttype
     *
     * @mbggenerated
     */
    public Integer getReceipttype() {
        return receipttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.receipttype
     *
     * @param receipttype the value for ch_sell_pool.receipttype
     *
     * @mbggenerated
     */
    public void setReceipttype(Integer receipttype) {
        this.receipttype = receipttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.delivery
     *
     * @return the value of ch_sell_pool.delivery
     *
     * @mbggenerated
     */
    public Integer getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.delivery
     *
     * @param delivery the value for ch_sell_pool.delivery
     *
     * @mbggenerated
     */
    public void setDelivery(Integer delivery) {
        this.delivery = delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.deliverytime
     *
     * @return the value of ch_sell_pool.deliverytime
     *
     * @mbggenerated
     */
    public String getDeliverytime() {
        return deliverytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.deliverytime
     *
     * @param deliverytime the value for ch_sell_pool.deliverytime
     *
     * @mbggenerated
     */
    public void setDeliverytime(String deliverytime) {
        this.deliverytime = deliverytime == null ? null : deliverytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.moq
     *
     * @return the value of ch_sell_pool.moq
     *
     * @mbggenerated
     */
    public String getMoq() {
        return moq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.moq
     *
     * @param moq the value for ch_sell_pool.moq
     *
     * @mbggenerated
     */
    public void setMoq(String moq) {
        this.moq = moq == null ? null : moq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.outmoq
     *
     * @return the value of ch_sell_pool.outmoq
     *
     * @mbggenerated
     */
    public String getOutmoq() {
        return outmoq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.outmoq
     *
     * @param outmoq the value for ch_sell_pool.outmoq
     *
     * @mbggenerated
     */
    public void setOutmoq(String outmoq) {
        this.outmoq = outmoq == null ? null : outmoq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.overflow
     *
     * @return the value of ch_sell_pool.overflow
     *
     * @mbggenerated
     */
    public String getOverflow() {
        return overflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.overflow
     *
     * @param overflow the value for ch_sell_pool.overflow
     *
     * @mbggenerated
     */
    public void setOverflow(String overflow) {
        this.overflow = overflow == null ? null : overflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.source
     *
     * @return the value of ch_sell_pool.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.source
     *
     * @param source the value for ch_sell_pool.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.lastPriceType
     *
     * @return the value of ch_sell_pool.lastPriceType
     *
     * @mbggenerated
     */
    public Integer getLastpricetype() {
        return lastpricetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.lastPriceType
     *
     * @param lastpricetype the value for ch_sell_pool.lastPriceType
     *
     * @mbggenerated
     */
    public void setLastpricetype(Integer lastpricetype) {
        this.lastpricetype = lastpricetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.lastPrice
     *
     * @return the value of ch_sell_pool.lastPrice
     *
     * @mbggenerated
     */
    public BigDecimal getLastprice() {
        return lastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.lastPrice
     *
     * @param lastprice the value for ch_sell_pool.lastPrice
     *
     * @mbggenerated
     */
    public void setLastprice(BigDecimal lastprice) {
        this.lastprice = lastprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.lastCustomerId
     *
     * @return the value of ch_sell_pool.lastCustomerId
     *
     * @mbggenerated
     */
    public Integer getLastcustomerid() {
        return lastcustomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.lastCustomerId
     *
     * @param lastcustomerid the value for ch_sell_pool.lastCustomerId
     *
     * @mbggenerated
     */
    public void setLastcustomerid(Integer lastcustomerid) {
        this.lastcustomerid = lastcustomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.lastMallAccount
     *
     * @return the value of ch_sell_pool.lastMallAccount
     *
     * @mbggenerated
     */
    public String getLastmallaccount() {
        return lastmallaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.lastMallAccount
     *
     * @param lastmallaccount the value for ch_sell_pool.lastMallAccount
     *
     * @mbggenerated
     */
    public void setLastmallaccount(String lastmallaccount) {
        this.lastmallaccount = lastmallaccount == null ? null : lastmallaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.lastCustomerName
     *
     * @return the value of ch_sell_pool.lastCustomerName
     *
     * @mbggenerated
     */
    public String getLastcustomername() {
        return lastcustomername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.lastCustomerName
     *
     * @param lastcustomername the value for ch_sell_pool.lastCustomerName
     *
     * @mbggenerated
     */
    public void setLastcustomername(String lastcustomername) {
        this.lastcustomername = lastcustomername == null ? null : lastcustomername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.poolPriceCount
     *
     * @return the value of ch_sell_pool.poolPriceCount
     *
     * @mbggenerated
     */
    public Integer getPoolpricecount() {
        return poolpricecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.poolPriceCount
     *
     * @param poolpricecount the value for ch_sell_pool.poolPriceCount
     *
     * @mbggenerated
     */
    public void setPoolpricecount(Integer poolpricecount) {
        this.poolpricecount = poolpricecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.lastTime
     *
     * @return the value of ch_sell_pool.lastTime
     *
     * @mbggenerated
     */
    public String getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.lastTime
     *
     * @param lasttime the value for ch_sell_pool.lastTime
     *
     * @mbggenerated
     */
    public void setLasttime(String lasttime) {
        this.lasttime = lasttime == null ? null : lasttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.isConfirm
     *
     * @return the value of ch_sell_pool.isConfirm
     *
     * @mbggenerated
     */
    public Integer getIsconfirm() {
        return isconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.isConfirm
     *
     * @param isconfirm the value for ch_sell_pool.isConfirm
     *
     * @mbggenerated
     */
    public void setIsconfirm(Integer isconfirm) {
        this.isconfirm = isconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.orderId
     *
     * @return the value of ch_sell_pool.orderId
     *
     * @mbggenerated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.orderId
     *
     * @param orderid the value for ch_sell_pool.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.priceType
     *
     * @return the value of ch_sell_pool.priceType
     *
     * @mbggenerated
     */
    public Integer getPricetype() {
        return pricetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.priceType
     *
     * @param pricetype the value for ch_sell_pool.priceType
     *
     * @mbggenerated
     */
    public void setPricetype(Integer pricetype) {
        this.pricetype = pricetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.isClose
     *
     * @return the value of ch_sell_pool.isClose
     *
     * @mbggenerated
     */
    public Integer getIsclose() {
        return isclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.isClose
     *
     * @param isclose the value for ch_sell_pool.isClose
     *
     * @mbggenerated
     */
    public void setIsclose(Integer isclose) {
        this.isclose = isclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.initPrice
     *
     * @return the value of ch_sell_pool.initPrice
     *
     * @mbggenerated
     */
    public BigDecimal getInitprice() {
        return initprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.initPrice
     *
     * @param initprice the value for ch_sell_pool.initPrice
     *
     * @mbggenerated
     */
    public void setInitprice(BigDecimal initprice) {
        this.initprice = initprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.FuturesMonth
     *
     * @return the value of ch_sell_pool.FuturesMonth
     *
     * @mbggenerated
     */
    public String getFuturesmonth() {
        return futuresmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.FuturesMonth
     *
     * @param futuresmonth the value for ch_sell_pool.FuturesMonth
     *
     * @mbggenerated
     */
    public void setFuturesmonth(String futuresmonth) {
        this.futuresmonth = futuresmonth == null ? null : futuresmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ch_sell_pool.initPriceType
     *
     * @return the value of ch_sell_pool.initPriceType
     *
     * @mbggenerated
     */
    public Integer getInitpricetype() {
        return initpricetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ch_sell_pool.initPriceType
     *
     * @param initpricetype the value for ch_sell_pool.initPriceType
     *
     * @mbggenerated
     */
    public void setInitpricetype(Integer initpricetype) {
        this.initpricetype = initpricetype;
    }
}